New 515 instructions
willox/dmasm pull request #7
Opened 2024-07-28 02:38 UTC by checkraisefold

Closes https://github.com/willox/auxtools/issues/88
Closes https://github.com/willox/auxtools/issues/89

also fixes other issues with 515 disassembly

2025-01-25 03:42 UTC, Absolucy requested changes

2025-01-25 03:42 UTC, Absolucy commented on src/access_modifiers.rs
> +    value >= 0xFFCD && value <= 0xFFEF
```suggestion
    (0xFFCD..=0xFFEF).contains(&value)
```

2025-01-25 04:39 UTC, checkraisefold commented on src/access_modifiers.rs
> +    value >= 0xFFCD && value <= 0xFFEF
fixed in other branch

2025-02-09 19:30 UTC, Absolucy approved these changes

2025-02-09 19:31 UTC, merged